// Autogenerated from MonoDevelop.Core.addin.xml

using System.Reflection;
using System.Runtime.CompilerServices;

[assembly: AssemblyProduct ("DotDevelop")]
[assembly: AssemblyTitle ("DotDevelop Runtime")]
[assembly: AssemblyDescription ("Provides the core services of the DotDevelop platform")]
[assembly: AssemblyVersion ("2.6")]
[assembly: AssemblyCopyright ("MIT/X11")]